<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-OE2GFHCN" failures="2" tests="2" name="Test" time="22.948" errors="0" timestamp="2021-04-13T16:41:38 CEST">
  <testcase classname="company.ValidateTitle" name="homepage" time="0.224">
    <failure type="junit.framework.ComparisonFailure" message="expected:&amp;lt;...&amp;gt; but was:&amp;lt;...123&amp;gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<...> but was:<...123>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at company.ValidateTitle.homepage(ValidateTitle.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1380)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.base/java.lang.Thread.run(Thread.java:844)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- homepage -->
  <testcase classname="company.ValidateTitle" name="homepage" time="0.241">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at resources.baseClass.getScreenshotPath(baseClass.java:48)
at company.Listeners.onTestFailure(Listeners.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1380)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.base/java.lang.Thread.run(Thread.java:844)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- homepage -->
</testsuite> <!-- Test -->
